import Waveform from "./Waveform";

export default function EmailPreview({ email = null }: { email?: any }) {
  return (
    <section className="mx-auto w-full max-w-6xl px-6 py-20 sm:px-8">
      <div className="grid grid-cols-1 items-center gap-12 lg:grid-cols-2">
        <div>
          <span className="font-[family-name:var(--font-mono)] text-xs uppercase tracking-[0.2em] text-[var(--accent)]">
            First supported action
          </span>
          <h2 className="mt-4 font-[family-name:var(--font-display)] text-3xl tracking-tight text-[var(--text-primary)] sm:text-4xl">
            Email, drafted while you talk
          </h2>
          <p className="mt-4 max-w-md leading-relaxed text-[var(--text-secondary)]">
            Say who it&rsquo;s for and what it&rsquo;s about. Vox writes a
            complete, professional email in real time — subject line,
            greeting, and body included — ready for you to review.
          </p>
        </div>

        <div className="rounded-2xl border border-[var(--border)] bg-[var(--bg-card)] shadow-[0_20px_60px_rgba(22,20,15,0.06)] dark:shadow-[0_20px_60px_rgba(0,0,0,0.4)]">
          <div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-3.5">
            <div className="flex items-center gap-2">
              <span className="h-2.5 w-2.5 rounded-full bg-[var(--border)]" />
              <span className="h-2.5 w-2.5 rounded-full bg-[var(--border)]" />
              <span className="h-2.5 w-2.5 rounded-full bg-[var(--border)]" />
            </div>
            <div className="flex items-center gap-1.5 rounded-full bg-[var(--accent-light)] px-2.5 py-1 font-[family-name:var(--font-mono)] text-[10px] uppercase tracking-wide text-[var(--accent)]">
              <Waveform bars={3} tone="signal" className="h-2.5" />
              Generated by Vox
            </div>
          </div>

          <div className="space-y-3 px-5 pt-4 text-sm">
            <div className="flex gap-2 border-b border-[var(--border-light)] pb-3">
              <span className="w-14 shrink-0 font-[family-name:var(--font-mono)] text-xs text-[var(--text-muted)]">
                To
              </span>
              <span className="text-[var(--text-primary)]">jared@company.com</span>
            </div>
            <div className="flex gap-2 border-b border-[var(--border-light)] pb-3">
              <span className="w-14 shrink-0 font-[family-name:var(--font-mono)] text-xs text-[var(--text-muted)]">
                Subject
              </span>
              <span className="font-medium text-[var(--text-primary)]">
                UI complete — ready for testing tomorrow
              </span>
            </div>
          </div>

          <div className="whitespace-pre-line px-5 pb-6 pt-4 text-sm leading-relaxed text-[var(--text-secondary)]">
<pre className="whitespace-pre-wrap font-sans leading-relaxed">
  {`Hi Jared,

The UI work is complete and ready for your review. It'll be available for testing starting tomorrow.

Best,
Alex`}
</pre>
          </div>
        </div>
      </div>
    </section>
  );
}
